import Head from "next/head";
import "./globals.css";

export const metadata = {
  title: "Logoipsum - Landing Page",
  description: "Generated by create next app",
  icon: "/ico.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href={metadata.icon} />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className="min-h-screen">{children}</body>
    </html>
  );
}
